export const GET_ALL_FOODS = "GET_ALL_FOODS";
export const GET_ALL_PANIER = "GET_ALL_PANIER";
export const SELECT_FOODS = "SELECT_FOODS";
export const ADD_USER = "ADD_USER";
export const DELETE_FOODS = "DELETE_FOODS";
export const SUM_PANIER = "SUM_PANIER";
export const TOT_PRIX = "TOT_PRIX";
export const PLUS_UN = "PLUS_UN";
export const MOINS_UN = "MOINS_UN";
export const GET_ALL_USER ="GET_ALL_USER"